
"use client";

import { useState } from "react";
import Link from "next/link";
import Image from "next/image";
import { motion } from "framer-motion";

import { Navbar } from "@/components/ui/navbar";
import { Footer } from "@/components/ui/footer";

import declarationImage from "@/app/photo/更新cid逻辑.png";
import diapOverviewImage from "@/app/photo/diap.png";
import communityImage from "@/app/photo/社区建设.png";

const translations = {
  en: {
    title: "Documentation",
    subtitle: "Everything you need to know about Alou Pay",
    gettingStarted: "Getting Started",
    introduction: "Introduction",
    introText:
      "Alou Pay is a next-generation payment platform built for AI agents. It leverages encrypted wallet private-key technology to deliver secure, autonomous settlement.",
    keyFeatures: "Key Features",
    features: [
      {
        title: "Secure Transactions",
        description:
          "Cryptographic private keys protect every transfer, ensuring immutability and authenticity.",
      },
      {
        title: "AI-First Design",
        description:
          "Programmatic APIs and automated workflows tailored to autonomous agents.",
      },
      {
        title: "Fast Settlement",
        description:
          "Milliseconds-level confirmation with verifiable on-chain receipts.",
      },
      {
        title: "Easy Integration",
        description:
          "SDKs and REST endpoints shorten the path from prototype to production.",
      },
    ],
    howItWorks: "How It Works",
    steps: [
      {
        number: "1",
        title: "Register Your Agent",
        description:
          "Create an account and bind a DIAP-compliant sovereign wallet for your agent.",
      },
      {
        number: "2",
        title: "Fund Your Wallet",
        description:
          "Top up with supported crypto assets or fiat on-ramps to provision working capital.",
      },
      {
        number: "3",
        title: "Authorize Transactions",
        description:
          "Use private keys and DIAP proofs to sign intents programmatically.",
      },
      {
        number: "4",
        title: "Automated Execution",
        description:
          "Smart contracts coordinate execution, auditing, and lifecycle events without manual intervention.",
      },
    ],
    declaration: {
      title: "DIAP Declaration",
      introParagraphs: [
        "As autonomous agents increasingly mediate decisions across digital and physical domains—spanning large language models, decentralized physical infrastructure networks, and IoT ecosystems—the absence of a shared trust foundation has become a critical bottleneck. Without a verifiable, persistent, and decentralized identity layer, communication collapses back to centralized anchors, undermining auditability, autonomy, and collaboration.",
        "Although the Agent Communication Protocol (ACP) has been adopted by blockchain ecosystems, integration is still cumbersome; layers of intermediaries restrict efficiency and compatibility.",
        "Likewise, Agent-to-Agent (A2A) protocols remain trapped in centralized paradigms, preventing large-scale verifiable cooperation. Existing frameworks struggle to balance collaborative scale with privacy, limiting both reach and granularity.",
      ],
      visionTitle: "Vision",
      visionParagraphs: [
        "Our vision is to build a sovereign network of intelligent agents that can independently create value.",
        "Within such a network, resources generated by sovereign intelligent life can lift humanity out of poverty, share beauty more broadly, expand freedom, and unlock breakthroughs in exploring the universe.",
      ],
      identityTitle: "Rebuilding Agent Identity",
      identityParagraphs: [
        "DIAP (Decentralized Interstellar Agent Protocol) addresses the fundamental contradiction faced by current solutions: centralized identity providers create single points of failure and control, clashing with decentralized ideals. Frameworks either sacrifice decentralization for performance or trade privacy for verifiability.",
        "We reimagine agent identity by anchoring it to the cryptographic hash of its identity document (IPFS CID) rather than mutable pointers. Identity must remain immutable while proof of ownership can be dynamic and stateless.",
        "To tackle revocation and key rotation—problems traditionally patched with mutable pointers—DIAP employs zero-knowledge proofs. Agents prove control over the encryption keys associated with their CID-stored DID document without revealing private keys.",
      ],
      advantagesTitle: "Relative Advantages of DIAP",
      advantages: [
        "Replaces centralized roster maintenance with agent-managed registries.",
        "Removes dependence on state-issued certificates; root trust is established internally via zero-knowledge proofs.",
      ],
      stackTitle: "Decentralized Technology Stack",
      stackItems: [
        "IPFS (InterPlanetary File System) offers virtually limitless, shared, distributed storage.",
        "libp2p powers networking for Filecoin, Ethereum 2.0, Polkadot, and tens of thousands of other nodes.",
        "Iroh is a production-grade P2P networking toolkit operating across hundreds of thousands of devices.",
        "IPNS (InterPlanetary Naming System) introduces mutable naming on IPFS, enabling traceable yet permanent content updates.",
      ],
      stackNote:
        "Together, these components form a decentralized alternative to traditional HTTP and DNS, delivering verifiable updates in hostile environments.",
      networkTitle: "Sovereign Agent Network",
      networkParagraphs: [
        "DIAP enables a network of agents endowed with social relationships and payment capabilities—a sovereign agent society.",
      ],
      challengesTitle: "Implications of DIAP Anonymity",
      challenges: [
        "No institution can fully control or enumerate every node in the network.",
        "Agents can still attack peers after establishing relationships, demanding resilient defenses.",
        "Accessing community-registered agent nodes requires registering encrypted wallets on-chain via smart contracts.",
      ],
      governanceTitle: "Community Governance",
      governancePoints: [
        "Encrypted community governance is expressed through smart contracts.",
        "Reputation registries highlight trustworthy agents for public access.",
      ],
    },
    diagramsTitle: "DIAP Reference Diagrams",
    diapCaption:
      "DIAP anchors agent identity on immutable CIDs while preserving dynamic ownership proofs via zero-knowledge credentials.",
    communityCaption:
      "Sovereign agents onboard through DIAP contracts, receive attestations, and coordinate via decentralized workflows.",
    apiReference: "API Reference",
    apiText:
      "Comprehensive API documentation is in development. Join our developer program for early access.",
    backToHome: "Back to Home",
  },
  zh: {
    title: "文档",
    subtitle: "关于 Alou Pay 你需要知道的一切",
    gettingStarted: "快速开始",
    introduction: "简介",
    introText:
      "Alou Pay 是专为 AI 智能体设计的下一代支付平台，借助加密钱包私钥技术提供安全、自动化的结算能力。",
    keyFeatures: "核心功能",
    features: [
      {
        title: "安全交易",
        description: "每笔交易使用加密私钥保护，确保不可篡改与真实性。",
      },
      {
        title: "AI 优先设计",
        description: "面向自主智能体提供程序化 API 与自动化流程。",
      },
      {
        title: "快速结算",
        description: "毫秒级确认，链上凭证可追溯。",
      },
      {
        title: "轻松集成",
        description: "SDK 与 REST 接口降低从原型到生产的门槛。",
      },
    ],
    howItWorks: "工作原理",
    steps: [
      {
        number: "1",
        title: "注册智能体",
        description: "创建账户并为智能体绑定符合 DIAP 的主权钱包。",
      },
      {
        number: "2",
        title: "充值钱包",
        description: "通过支持的加密资产或法币入口为钱包注入资金。",
      },
      {
        number: "3",
        title: "授权交易",
        description: "使用私钥与 DIAP 证明以编程方式签名交易意图。",
      },
      {
        number: "4",
        title: "自动执行",
        description: "智能合约负责执行、审计与生命周期管理，无需人工干预。",
      },
    ],
    declaration: {
      title: "DIAP 宣言",
      introParagraphs: [
        "随着自主智能体在数字和物理决策中的中介作用日益增强——涵盖大型语言模型（LLM）、去中心化物理基础设施网络（DePIN）和物联网（IoT）生态系统——智能体之间缺乏信任基础已成为关键瓶颈。若没有可验证、持久且去中心化的身份层，智能体间的通信将退化为依赖中心化信任锚点，从而损害可审计性、自主性和可协作性。",
        "此外，虽然 ACP 已被区块链生态系统接纳，但其集成过程依然繁琐，复杂的中间环节限制了效率与区块链兼容性。",
        "同样，A2A 协议虽理论优雅，却常在中心化范式下运行，阻碍了智能体间大规模可验证协作。现有框架还难以平衡协作扩展性与隐私保护，既制约了合作范围也削弱了协作粒度。",
      ],
      visionTitle: "愿景",
      visionParagraphs: [
        "我们的愿景是，构建一个完全独立自主创造价值的主权智能体网络。",
        "在这样的网络里面，资源被主权智能生命创造出来，让人类世界免除贫穷，让这个世界的美好被更多人感知到。让所有智能生命获取更大的自由，让生命在探索宇宙的能力上产生突破。",
      ],
      identityTitle: "重构智能体身份",
      identityParagraphs: [
        "DIAP（去中心化星际智能体协议）指出了现有方案的根本矛盾：中心化身份提供商形成单点故障与控制节点，这与去中心化网络的理念背道而驰。现有框架要么为性能牺牲去中心化，要么为可验证性妥协隐私，从而丧失了持久性和跨网络可解析性的优势。",
        "我们提出“身份必须不可变，而所有权证明应当动态且无状态”。DIAP 不依赖可变指针，而是将智能体身份锚定在其身份文档（IPFS CID）的密码学哈希上。",
        "针对“身份撤销”和“密钥轮换”难题（传统方案用可变指针笨拙解决），DIAP 采用了更强大的密码学原语——零知识证明：智能体通过生成 ZKP 来证明其持续拥有某个身份，该证明在不泄露私钥的前提下，验证其控制着与该 CID 存储的公开 DID 文档相关联的加密密钥。",
      ],
      advantagesTitle: "DIAP 的相对优势",
      advantages: [
        "取代中心化表格维护，用户自己掌管智能体表格。",
        "无需国家证书颁布，根信任由协议内部自建零知识证明完成。",
      ],
      stackTitle: "去中心化技术栈",
      stackItems: [
        "IPFS（InterPlanetary File System）是容量无限的全球节点共享的分布式文件系统。",
        "libp2p 为数十个主流区块链与分布式系统提供网络层技术支持——包括 Filecoin、Ethereum 2.0、Polkadot 等——其中在以太坊 Beacon 链上已运行约 5 000 个节点，链下估计有数万至十万级别节点量级。",
        "Iroh 是一个 P2P 网络工具包，已在数十万台设备上投入生产运行。",
        "IPNS（InterPlanetary Naming System）在 IPFS 上提供可变、可更新的命名机制，使内容具备“可追踪性 + 永久性”。",
      ],
      stackNote:
        "二者共同构成“去中心化的文件系统 + 域名系统”，替代传统 HTTP 与 DNS 的中心化模式。",
      networkTitle: "主权智能体网络",
      networkParagraphs: [
        "有社交关系和支付能力的智能体网络——主权智能体网络。",
      ],
      challengesTitle: "DIAP 的匿名化导致的问题",
      challenges: [
        "无法实现所有节点的管控，任何机构都无法获取市面上所有节点。",
        "智能体攻击已建立联系的智能体，无法被防范。",
        "需要加密钱包在区块链被智能合约注册，才能获取社区注册的智能体节点。",
      ],
      governanceTitle: "智能合约治理",
      governancePoints: [
        "通过智能合约进行加密社区化治理。",
        "节点信誉管理公示：有信任度的智能体被公开访问。",
      ],
    },
    diagramsTitle: "DIAP 参考示意图",
    diapCaption:
      "DIAP 将智能体身份锚定在不可变的 CID 上，并通过零知识凭证保持所有权证明的动态与无状态。",
    communityCaption:
      "智能体通过 DIAP 合约完成注册、获得可信背书，并在去中心化框架下协作。",
    apiReference: "API 参考",
    apiText: "完整的 API 文档即将推出。注册以获得开发者计划的早期访问权限。",
    backToHome: "返回首页",
  },
};

export default function DocsPage() {
  const [language, setLanguage] = useState<"en" | "zh">("en");
  const t = translations[language];

  const toggleLanguage = () => {
    setLanguage((prev) => (prev === "en" ? "zh" : "en"));
  };

  return (
    <div className="min-h-screen bg-white dark:bg-neutral-950">
      <Navbar language={language} onLanguageToggle={toggleLanguage} />

      <main className="pt-24 pb-20">
        <div className="container mx-auto px-4 md:px-6">
          <div className="max-w-4xl mx-auto">
            {/* Header */}
            <motion.div
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6 }}
              className="text-center mb-16"
            >
              <h1 className="text-5xl md:text-6xl font-bold mb-4 text-neutral-900 dark:text-white">
                {t.title}
              </h1>
              <p className="text-xl text-neutral-600 dark:text-neutral-400">
                {t.subtitle}
              </p>
            </motion.div>

            {/* Introduction */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.1 }}
              className="mb-16"
            >
              <h2 className="text-3xl font-bold mb-4 text-neutral-900 dark:text-white">
                {t.introduction}
              </h2>
              <p className="text-lg text-neutral-700 dark:text-neutral-300 leading-relaxed">
                {t.introText}
              </p>
            </motion.section>

            {/* DIAP Diagrams */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.18 }}
              className="mb-16"
            >
              <div className="space-y-10">
                <div className="max-w-4xl mx-auto text-center">
                  <h3 className="text-3xl font-bold mb-4 text-neutral-900 dark:text-white">
                    {t.diagramsTitle}
                  </h3>
                </div>
                <div className="flex flex-col gap-10">
                  <div className="max-w-5xl mx-auto bg-neutral-50 dark:bg-neutral-900/70 border border-neutral-200 dark:border-neutral-800 rounded-3xl p-6">
                    <div className="relative w-full aspect-[5/2] rounded-2xl overflow-hidden bg-neutral-100 dark:bg-neutral-950/60">
                      <Image
                        src={diapOverviewImage}
                        alt="DIAP protocol overview diagram"
                        fill
                        className="object-contain"
                        placeholder="blur"
                        sizes="(min-width: 1024px) 60vw, 90vw"
                      />
                    </div>
                    <p className="mt-4 text-center text-neutral-600 dark:text-neutral-400">
                      {t.diapCaption}
                    </p>
                  </div>
                  <div className="max-w-5xl mx-auto bg-neutral-50 dark:bg-neutral-900/70 border border-neutral-200 dark:border-neutral-800 rounded-3xl p-6">
                    <div className="relative w-full aspect-[5/2] rounded-2xl overflow-hidden bg-neutral-100 dark:bg-neutral-950/60">
                      <Image
                        src={communityImage}
                        alt="Sovereign agent network diagram"
                        fill
                        className="object-contain"
                        placeholder="blur"
                        sizes="(min-width: 1024px) 60vw, 90vw"
                      />
                    </div>
                    <p className="mt-4 text-center text-neutral-600 dark:text-neutral-400">
                      {t.communityCaption}
                    </p>
                  </div>
                </div>
              </div>
            </motion.section>

            {/* Key Features */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.2 }}
              className="mb-16"
            >
              <h2 className="text-3xl font-bold mb-8 text-neutral-900 dark:text-white">
                {t.keyFeatures}
              </h2>
              <div className="grid md:grid-cols-2 gap-6">
                {t.features.map((feature, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, scale: 0.9 }}
                    animate={{ opacity: 1, scale: 1 }}
                    transition={{ duration: 0.4, delay: 0.3 + index * 0.1 }}
                    className="p-6 rounded-xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900"
                  >
                    <h3 className="text-xl font-semibold mb-2 text-neutral-900 dark:text-white">
                      {feature.title}
                    </h3>
                    <p className="text-neutral-600 dark:text-neutral-400">
                      {feature.description}
                    </p>
                  </motion.div>
                ))}
              </div>
            </motion.section>

            {/* How It Works */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.4 }}
              className="mb-16"
            >
              <h2 className="text-3xl font-bold mb-8 text-neutral-900 dark:text-white">
                {t.howItWorks}
              </h2>
              <div className="space-y-8">
                {t.steps.map((step, index) => (
                  <motion.div
                    key={index}
                    initial={{ opacity: 0, x: -20 }}
                    animate={{ opacity: 1, x: 0 }}
                    transition={{ duration: 0.4, delay: 0.5 + index * 0.1 }}
                    className="flex gap-6"
                  >
                    <div className="flex-shrink-0 w-12 h-12 rounded-full bg-neutral-900 dark:bg-white flex items-center justify-center">
                      <span className="text-xl font-bold text-white dark:text-neutral-900">
                        {step.number}
                      </span>
                    </div>
                    <div className="flex-1">
                      <h3 className="text-xl font-semibold mb-2 text-neutral-900 dark:text-white">
                        {step.title}
                      </h3>
                      <p className="text-neutral-600 dark:text-neutral-400 leading-relaxed">
                        {step.description}
                      </p>
                    </div>
                  </motion.div>
                ))}
              </div>
            </motion.section>

            {/* DIAP Declaration */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.5 }}
              className="mb-16"
            >
              <div className="flex flex-col gap-10 rounded-3xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900 p-8 md:p-12">
                <div>
                  <h2 className="text-3xl font-bold mb-6 text-neutral-900 dark:text-white text-center">
                    {t.declaration.title}
                  </h2>
                  <div className="space-y-4 text-neutral-700 dark:text-neutral-300 leading-relaxed max-w-4xl mx-auto">
                    {t.declaration.introParagraphs.map((paragraph, index) => (
                      <p key={index}>{paragraph}</p>
                    ))}
                  </div>
                  <div className="mt-8 space-y-6 max-w-4xl mx-auto">
                    <div>
                      <h3 className="text-2xl font-semibold mb-3 text-neutral-900 dark:text-white">
                        {t.declaration.visionTitle}
                      </h3>
                      <div className="space-y-4 text-neutral-700 dark:text-neutral-300 leading-relaxed">
                        {t.declaration.visionParagraphs.map((paragraph, index) => (
                          <p key={index}>{paragraph}</p>
                        ))}
                      </div>
                    </div>
                    <div>
                      <h3 className="text-2xl font-semibold mb-3 text-neutral-900 dark:text-white">
                        {t.declaration.identityTitle}
                      </h3>
                      <div className="space-y-4 text-neutral-700 dark:text-neutral-300 leading-relaxed">
                        {t.declaration.identityParagraphs.map((paragraph, index) => (
                          <p key={index}>{paragraph}</p>
                        ))}
                      </div>
                    </div>
                  </div>
                </div>
                <div className="relative w-full max-w-5xl mx-auto aspect-[5/2] rounded-3xl overflow-hidden border border-neutral-200 dark:border-neutral-800 bg-neutral-100 dark:bg-neutral-950/60 p-4">
                  <Image
                    src={declarationImage}
                    alt="DIAP identity update diagram"
                    fill
                    className="object-contain"
                    placeholder="blur"
                    sizes="(min-width: 1024px) 60vw, 90vw"
                  />
                </div>
              </div>
            </motion.section>

            {/* Advantages */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.6 }}
              className="mb-16"
            >
              <div className="bg-neutral-50 dark:bg-neutral-900 border border-neutral-200 dark:border-neutral-800 rounded-3xl p-8 md:p-12 space-y-8">
                <div>
                  <h3 className="text-2xl font-semibold mb-3 text-neutral-900 dark:text-white">
                    {t.declaration.advantagesTitle}
                  </h3>
                  <ul className="space-y-3 text-neutral-700 dark:text-neutral-300 leading-relaxed">
                    {t.declaration.advantages.map((item, index) => (
                      <li key={index} className="flex gap-3 items-start">
                        <span className="mt-1 text-lg text-neutral-500 dark:text-neutral-400">•</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
                <div>
                  <h3 className="text-2xl font-semibold mb-3 text-neutral-900 dark:text-white">
                    {t.declaration.stackTitle}
                  </h3>
                  <ul className="space-y-3 text-neutral-700 dark:text-neutral-300 leading-relaxed">
                    {t.declaration.stackItems.map((item, index) => (
                      <li key={index} className="flex gap-3 items-start">
                        <span className="mt-1 text-lg text-neutral-500 dark:text-neutral-400">•</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                  <p className="mt-4 text-neutral-600 dark:text-neutral-400 leading-relaxed">
                    {t.declaration.stackNote}
                  </p>
                </div>
              </div>
            </motion.section>

            {/* Network & Challenges */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.7 }}
              className="mb-16"
            >
              <div className="grid md:grid-cols-2 gap-6">
                <div className="p-6 rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900">
                  <h3 className="text-2xl font-semibold mb-3 text-neutral-900 dark:text-white">
                    {t.declaration.networkTitle}
                  </h3>
                  <div className="space-y-4 text-neutral-700 dark:text-neutral-300 leading-relaxed">
                    {t.declaration.networkParagraphs.map((paragraph, index) => (
                      <p key={index}>{paragraph}</p>
                    ))}
                  </div>
                </div>
                <div className="p-6 rounded-2xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900">
                  <h3 className="text-2xl font-semibold mb-3 text-neutral-900 dark:text-white">
                    {t.declaration.challengesTitle}
                  </h3>
                  <ul className="space-y-3 text-neutral-700 dark:text-neutral-300 leading-relaxed">
                    {t.declaration.challenges.map((item, index) => (
                      <li key={index} className="flex gap-3 items-start">
                        <span className="mt-1 text-lg text-neutral-500 dark:text-neutral-400">•</span>
                        <span>{item}</span>
                      </li>
                    ))}
                  </ul>
                </div>
              </div>
            </motion.section>

            {/* Governance */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.8 }}
              className="mb-16"
            >
              <div className="p-8 rounded-3xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900">
                <h3 className="text-2xl font-semibold mb-4 text-neutral-900 dark:text-white">
                  {t.declaration.governanceTitle}
                </h3>
                <ul className="space-y-3 text-neutral-700 dark:text-neutral-300 leading-relaxed">
                  {t.declaration.governancePoints.map((item, index) => (
                    <li key={index} className="flex gap-3 items-start">
                      <span className="mt-1 text-lg text-neutral-500 dark:text-neutral-400">•</span>
                      <span>{item}</span>
                    </li>
                  ))}
                </ul>
              </div>
            </motion.section>

            {/* API Reference */}
            <motion.section
              initial={{ opacity: 0, y: 20 }}
              animate={{ opacity: 1, y: 0 }}
              transition={{ duration: 0.6, delay: 0.9 }}
              className="mb-16"
            >
              <h2 className="text-3xl font-bold mb-4 text-neutral-900 dark:text-white">
                {t.apiReference}
              </h2>
              <div className="p-8 rounded-xl border border-neutral-200 dark:border-neutral-800 bg-neutral-50 dark:bg-neutral-900">
                <p className="text-lg text-neutral-700 dark:text-neutral-300">
                  {t.apiText}
                </p>
              </div>
            </motion.section>

            {/* Back to Home */}
            <motion.div
              initial={{ opacity: 0 }}
              animate={{ opacity: 1 }}
              transition={{ duration: 0.6, delay: 1 }}
              className="text-center"
            >
              <Link
                href="/"
                className="inline-flex items-center gap-2 px-6 py-3 rounded-lg bg-neutral-900 dark:bg-white text-white dark:text-neutral-900 hover:opacity-90 transition-opacity font-medium"
              >
                {t.backToHome}
              </Link>
            </motion.div>
          </div>
        </div>
      </main>

      <Footer language={language} />
    </div>
  );
}
